"""Create project, Task and complex_task classes. Added columns deadline, initial_date and finished_date to WorkItem class

Revision ID: 1dc54d09a3fc
Revises: e6b8714c8b58
Create Date: 2024-02-17 01:36:19.648794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc54d09a3fc'
down_revision: Union[str, None] = 'e6b8714c8b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complex_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('work_items', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('work_items', sa.Column('initial_dated', sa.DateTime(), nullable=True))
    op.add_column('work_items', sa.Column('finished_dated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_work_items_deadline'), 'work_items', ['deadline'], unique=False)
    op.create_index(op.f('ix_work_items_finished_dated'), 'work_items', ['finished_dated'], unique=False)
    op.create_index(op.f('ix_work_items_initial_dated'), 'work_items', ['initial_dated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_items_initial_dated'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_finished_dated'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_deadline'), table_name='work_items')
    op.drop_column('work_items', 'finished_dated')
    op.drop_column('work_items', 'initial_dated')
    op.drop_column('work_items', 'deadline')
    op.drop_table('tasks')
    op.drop_table('complex_tasks')
    op.drop_table('projects')
    # ### end Alembic commands ###
