"""Deleted work_item column type to redefine work_item_type enum

Revision ID: 3184c6990dc2
Revises: 40be1f3d1b39
Create Date: 2024-03-24 15:12:22.421603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3184c6990dc2'
down_revision: Union[str, None] = '40be1f3d1b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'work_item_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('work_item_type', postgresql.ENUM('EPIC', 'FEATURE', 'TASK', name='workitemtype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
