"""Soft delete for work_items and users.

Revision ID: 4cd240c206dc
Revises: 7c32ecae7de5
Create Date: 2024-02-21 03:57:25.870734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd240c206dc'
down_revision: Union[str, None] = '7c32ecae7de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
