"""Changed deadline column name to due_date

Revision ID: 694d6dc8a6e1
Revises: 15b8951057ce
Create Date: 2024-03-20 22:46:29.038933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694d6dc8a6e1'
down_revision: Union[str, None] = '15b8951057ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_work_items_deadline', table_name='work_items')
    op.create_index(op.f('ix_work_items_due_date'), 'work_items', ['due_date'], unique=False)
    op.drop_column('work_items', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_work_items_due_date'), table_name='work_items')
    op.create_index('ix_work_items_deadline', 'work_items', ['deadline'], unique=False)
    op.drop_column('work_items', 'due_date')
    # ### end Alembic commands ###
