"""Created WorkItem.status property

Revision ID: 7947107cceff
Revises: 679cc76efac4
Create Date: 2024-03-05 01:47:10.764892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7947107cceff'
down_revision: Union[str, None] = '679cc76efac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('status', sa.Enum('NEW', 'CLOSED', 'PAUSED', 'RUNNING', name='workitemstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'status')
    # ### end Alembic commands ###
