"""Corrected FK to managed_team relation (User) 2

Revision ID: d607c5c2c13b
Revises: b22119c7aa1e
Create Date: 2024-02-21 20:58:23.319042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd607c5c2c13b'
down_revision: Union[str, None] = 'b22119c7aa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
